### ISSUE TITLE
Theme doesn't work

### ISSUE THREAD

**Issue by RoiArthurB** [ChoccyHobNob/es-theme-cygnus#1]
Hi!

I love your theme, but when I try to use it, I've only a white screen... :/
I download it from the github link but it doesn't work...

Anyway, so if you could help me I'll be very happy :)

PS: I use Retropie 4.2 (the last version) on a Raspberry 3 - Model B, if it could help

**Comment by a8bit** [comment]
Go to retropie setup, manage packages, manage core packages, emulationstation, update from source code. Do an update. The theme now works. 

This theme uses the new carousel, z-index and video features of emulationstation that aren't yet available in a binary or image release of RetroPie
