### ISSUE TITLE
zIndex for "md_Image" too low

### ISSUE THREAD

**Issue by esmith13** [ChoccyHobNob/es-theme-cygnus#4]
The zIndex for "md_Image" should be set to 35 IMHO. When using the standard view that allows for a video, marquee and boxart to all show at once, larger boxart that overlaps the video appears behind the video instead of in front of the video like the marquee. I corrected this myself on my system by setting <zIndex>35</zIndex> for "md_Image". The default values in EmulationStation are 30 for video and images and 35 for marquee, therefore images need to be at least 31 to show on top of the video in case of overlap.

**Comment by a8bit** [comment]
It's set to 40 ¯\_(ツ)_/¯
